### ISSUE TITLE
Error during AOT build

### ISSUE THREAD

**Issue by zaalbarxx** [Alorel/ngforage#57] opened 2018-04-05 06:19 UTC
Hi!
I've updated package.json to use `ngforage@^2.0.0` along with `@angular/core@^5.0.0` and for some reason when trying to build with AOT I get following message:
![image](https://user-images.githubusercontent.com/3301242/38332017-2d64ed68-3855-11e8-95a4-ed4882b2be07.png)
Do you have any clue why it behaves like this ? I was trying with both 2.x and 3.x and the result is the same. However when I compile without AOT it works perfectly fine.

**Comment by zaalbarxx** [comment] 2018-04-05 07:59
I found that after removing this line from `ngforage.metadata.json` it works fine
![image](https://user-images.githubusercontent.com/3301242/38353776-cc91b2ba-38b7-11e8-8adb-288e6bb37106.png)
Not sure why this line is being added to metadata since `NgForageConfig` is explicitly set below in `origins` object, but as I said removing this makes the build finish properly.

**Comment by Alorel** [comment] 2018-04-05 08:17
Closing as a duplicate of #56 but thanks a lot for this report and especially the fix. I'll do some tests in the next couple of hours and release a patched version. :+1:

**Closed by Alorel** 2018-04-05 08:17 UTC
